[build]

publish = "dist/"
command = "npm run build"

[[redirects]]
 from = "/api/*"
 to = "https://api-puszcza.netlify.com/api/:splat"
 status = 200
 force = true

[[redirects]]
 from = "/admin/*"
 to = "https://api-puszcza.netlify.com/admin/:splat"
 status = 301
 force = true

[[redirects]]
 from = "/rss.xml"
 to = "https://api-puszcza.netlify.com/rss.xml"
 status = 200
 force = true

[[redirects]]
 from = "/net"
 to = "https://19pdh.github.io/puszczanet"
 status = 200
 force = true
